const { prisma } = require("../constats/config.js");
//ADD CATEGORIES AS SEED DATA
const seed = async () => {
  try {
    let currencies = await prisma.currency.findMany();
    if (!currencies.length) {
      //CREATING CURRENCIES CATALOG
      console.log("CREATING CURRENCIES CATALOG");
      await prisma.currency
        .createMany({
          data: [
            {
              code: "AED",
              name: "Emirati Dirham",
              symbol: ".د.ب",
              exp: 2,
              flag: "ae",
            },
            {
              code: "AFN",
              name: "Afghan Afghani",
              symbol: "؋",
              exp: 2,
              flag: "af",
            },
            {
              code: "ALL",
              name: "Albanian lek",
              symbol: "lek",
              exp: 2,
              flag: "al",
            },
            {
              code: "AMD",
              name: "Armenian dram",
              symbol: "AMD",
              exp: 2,
              flag: "am",
            },
            {
              code: "ANG",
              name: "Dutch Guilder",
              symbol: "ƒ",
              exp: 2,
              flag: "an",
            },
            {
              code: "AOA",
              name: "Angolan Kwanza",
              symbol: "Kz",
              exp: 2,
              flag: "ao",
            },
            {
              code: "ARS",
              name: "Argentine peso",
              symbol: "$",
              exp: 2,
              flag: "ar",
            },
            {
              code: "AUD",
              name: "Australian Dollar",
              symbol: "$",
              exp: 2,
              flag: "au",
            },
            {
              code: "AWG",
              name: "Arubin florin",
              symbol: "ƒ",
              exp: 2,
              flag: "aw",
            },
            {
              code: "AZN",
              name: "Azerbaijani manat",
              symbol: "ман",
              exp: 2,
              flag: "az",
            },
            {
              code: "BAM",
              name: "Bosnian Convertible Marka",
              symbol: "KM",
              exp: 2,
              flag: "ba",
            },
            {
              code: "BBD",
              name: "Barbadian dollar",
              symbol: "$",
              exp: 2,
              flag: "bb",
            },
            {
              code: "BDT",
              name: "Bangladeshi Taka",
              symbol: "Tk",
              exp: 2,
              flag: "bd",
            },
            {
              code: "BGN",
              name: "Bulgarian lev",
              symbol: "лв",
              exp: 2,
              flag: "bg",
            },
            {
              code: "BHD",
              name: "Bahraini Dinar",
              symbol: ".د.ب or BD",
              exp: 3,
              flag: "bh",
            },
            {
              code: "BIF",
              name: "Burundian Franc",
              symbol: "FBu",
              exp: 0,
              flag: "bi",
            },
            {
              code: "BMD",
              name: "Bermudian dollar",
              symbol: "$",
              exp: 2,
              flag: "bm",
            },
            {
              code: "BND",
              name: "Bruneian Dollar",
              symbol: "$",
              exp: 2,
              flag: "bn",
            },
            {
              code: "BOB",
              name: "Bolivian Boliviano",
              symbol: "$b",
              exp: 2,
              flag: "bo",
            },
            {
              code: "BRL",
              name: "Brazilian real",
              symbol: "R$",
              exp: 2,
              flag: "br",
            },
            {
              code: "BSD",
              name: "Bahamian dollar",
              symbol: "B$",
              exp: 2,
              flag: "bs",
            },
            {
              code: "BTN",
              name: "Bhutanese Ngultrum",
              symbol: "Nu.",
              exp: 2,
              flag: "bt",
            },
            {
              code: "BWP",
              name: "Botswana Pula",
              symbol: "P",
              exp: 2,
              flag: "bw",
            },
            {
              code: "BYR",
              name: "Belarusian ruble",
              symbol: "р",
              exp: 2,
              flag: "by",
            },
            {
              code: "BZD",
              name: "Belize dollar",
              symbol: "BZ$",
              exp: 2,
              flag: "bz",
            },
            {
              code: "CAD",
              name: "Canadian Dollar",
              symbol: "$",
              exp: 2,
              flag: "ca",
            },
            {
              code: "CHF",
              name: "Swiss Franc",
              symbol: "CHF",
              exp: 2,
              flag: "ch",
            },
            {
              code: "CLP",
              name: "Chilean Peso",
              symbol: "$",
              exp: 0,
              flag: "cl",
            },
            {
              code: "CNY",
              name: "Yuan or chinese renminbi",
              symbol: "¥",
              exp: 2,
              flag: "cn",
            },
            {
              code: "COP",
              name: "Colombian peso",
              symbol: "$",
              exp: 2,
              flag: "co",
            },
            {
              code: "CRC",
              name: "Costa Rican colón",
              symbol: "₡",
              exp: 2,
              flag: "cr",
            },
            {
              code: "CUC",
              name: "Cuban convertible peso",
              symbol: "$",
              exp: 2,
              flag: "cu",
            },
            {
              code: "CUP",
              name: "Cuban peso",
              symbol: "₱",
              exp: 2,
              flag: "cu",
            },
            {
              code: "CVE",
              name: "Cape Verdean Escudo",
              symbol: "$",
              exp: 0,
              flag: "cv",
            },
            {
              code: "CZK",
              name: "Czech koruna",
              symbol: "Kč",
              exp: 2,
              flag: "cz",
            },
            {
              code: "DJF",
              name: "Djiboutian Franc",
              symbol: "fdj",
              exp: 0,
              flag: "dj",
            },
            {
              code: "DKK",
              name: "Danish krone",
              symbol: "kr",
              exp: 2,
              flag: "dk",
            },
            {
              code: "DOP",
              name: "Dominican peso",
              symbol: "$",
              exp: 2,
              flag: "do",
            },
            {
              code: "DZD",
              name: "Algerian Dinar",
              symbol: "جد",
              exp: 2,
              flag: "dz",
            },
            {
              code: "EGP",
              name: "Egyptian Pound",
              symbol: "£ ",
              exp: 2,
              flag: "eg",
            },
            {
              code: "ERN",
              name: "Eritrean nakfa",
              symbol: "ናቕፋ",
              exp: 2,
              flag: "er",
            },
            {
              code: "ETB",
              name: "Ethiopian Birr",
              symbol: "Br",
              exp: 2,
              flag: "et",
            },
            { code: "EUR", name: "Euro", symbol: "€", exp: 2, flag: "eu" },
            {
              code: "FJD",
              name: "Fijian dollar",
              symbol: "$",
              exp: 2,
              flag: "fj",
            },
            {
              code: "FKP",
              name: "Falkland Island Pound",
              symbol: "£",
              exp: 2,
              flag: "fk",
            },
            {
              code: "GBP",
              name: "British Pound",
              symbol: "£",
              exp: 2,
              flag: "gb",
            },
            {
              code: "GEL",
              name: "Georgian lari",
              symbol: "ლ",
              exp: 2,
              flag: "ge",
            },
            {
              code: "GHS",
              name: "Ghanaian Cedi",
              symbol: "GH¢",
              exp: 2,
              flag: "gh",
            },
            {
              code: "GIP",
              name: "Gibraltar pound",
              symbol: "£",
              exp: 2,
              flag: "gi",
            },
            {
              code: "GMD",
              name: "Gambian dalasi",
              symbol: "D",
              exp: 2,
              flag: "gm",
            },
            {
              code: "GNF",
              name: "Guinean Franc",
              symbol: "GNF",
              exp: 0,
              flag: "gn",
            },
            {
              code: "GTQ",
              name: "Guatemalan Quetzal",
              symbol: "Q",
              exp: 2,
              flag: "gt",
            },
            {
              code: "GYD",
              name: "Guyanese dollar",
              symbol: "$",
              exp: 2,
              flag: "gy",
            },
            {
              code: "HKD",
              name: "Hong Kong dollar",
              symbol: "HK$",
              exp: 2,
              flag: "hk",
            },
            {
              code: "HNL",
              name: "Honduran lempira",
              symbol: "L",
              exp: 2,
              flag: "hn",
            },
            {
              code: "HRK",
              name: "Croatian kuna",
              symbol: "kn",
              exp: 2,
              flag: "hr",
            },
            {
              code: "HTG",
              name: "Haitian gourde",
              symbol: "G",
              exp: 2,
              flag: "ht",
            },
            {
              code: "HUF",
              name: "Hungarian forint",
              symbol: "Ft",
              exp: 2,
              flag: "hu",
            },
            {
              code: "IDR",
              name: "Indonesian Rupiah",
              symbol: "Rp",
              exp: 2,
              flag: "id",
            },
            {
              code: "ILS",
              name: "Israeli Shekel",
              symbol: "₪",
              exp: 2,
              flag: "il",
            },
            {
              code: "INR",
              name: "Indian Rupee",
              symbol: "₹",
              exp: 2,
              flag: "in",
            },
            {
              code: "IQD",
              name: "Iraqi Dinar",
              symbol: "ع.د",
              exp: 3,
              flag: "iq",
            },
            {
              code: "IRR",
              name: "Iranian Rial",
              symbol: "﷼",
              exp: 2,
              flag: "ir",
            },
            {
              code: "ISK",
              name: "Icelandic Krona",
              symbol: "kr",
              exp: 0,
              flag: "is",
            },
            {
              code: "JMD",
              name: "Jamaican dollar",
              symbol: "J$",
              exp: 2,
              flag: "jm",
            },
            {
              code: "JOD",
              name: "Jordanian Dinar",
              symbol: "JOD",
              exp: 3,
              flag: "jo",
            },
            {
              code: "JPY",
              name: "Japanese yen",
              symbol: "¥",
              exp: 0,
              flag: "jp",
            },
            {
              code: "KES",
              name: "Kenyan Shilling",
              symbol: "KSh",
              exp: 2,
              flag: "ke",
            },
            {
              code: "KGS",
              name: "Kyrgyzstani som",
              symbol: "лв",
              exp: 2,
              flag: "kg",
            },
            {
              code: "KHR",
              name: "Cambodian Riel",
              symbol: "៛",
              exp: 2,
              flag: "kh",
            },
            {
              code: "KMF",
              name: "Comoro Franc",
              symbol: "KMF",
              exp: 0,
              flag: "km",
            },
            {
              code: "KPW",
              name: "North Korean won",
              symbol: "₩",
              exp: 2,
              flag: "kp",
            },
            {
              code: "KRW",
              name: "South Korean won",
              symbol: "₩",
              exp: 0,
              flag: "kr",
            },
            {
              code: "KWD",
              name: "Kuwaiti Dinar",
              symbol: "ك",
              exp: 3,
              flag: "kw",
            },
            {
              code: "KYD",
              name: "Caymanian Dollar",
              symbol: "$",
              exp: 2,
              flag: "ky",
            },
            {
              code: "KZT",
              name: "Kazakhstani tenge",
              symbol: "₸",
              exp: 2,
              flag: "kz",
            },
            {
              code: "LAK",
              name: "Lao or Laotian Kip",
              symbol: "₭",
              exp: 2,
              flag: "la",
            },
            {
              code: "LBP",
              name: "Lebanese Pound",
              symbol: "ل.ل",
              exp: 2,
              flag: "lb",
            },
            {
              code: "LKR",
              name: "Sri Lankan Rupee",
              symbol: "Rs",
              exp: 2,
              flag: "lk",
            },
            {
              code: "LRD",
              name: "Liberian Dollar",
              symbol: "$",
              exp: 2,
              flag: "lr",
            },
            {
              code: "LSL",
              name: "Lesotho loti",
              symbol: "L or M",
              exp: 2,
              flag: "ls",
            },
            {
              code: "LTL",
              name: "Lithuanian litas",
              symbol: "Lt",
              exp: 2,
              flag: "lt",
            },
            {
              code: "LYD",
              name: "Libyan Dinar",
              symbol: " د.ل",
              exp: 3,
              flag: "ly",
            },
            {
              code: "MAD",
              name: "Moroccan Dirham",
              symbol: "م.د.",
              exp: 2,
              flag: "ma",
            },
            {
              code: "MDL",
              name: "Moldovan Leu",
              symbol: "L",
              exp: 2,
              flag: "md",
            },
            {
              code: "MGA",
              name: "Malagasy Ariary",
              symbol: "Ar",
              exp: 2,
              flag: "mg",
            },
            {
              code: "MKD",
              name: "Macedonian Denar",
              symbol: "ден",
              exp: 2,
              flag: "mk",
            },
            {
              code: "MMK",
              name: "Burmese Kyat",
              symbol: "K",
              exp: 2,
              flag: "mm",
            },
            {
              code: "MNT",
              name: "Mongolian Tughrik",
              symbol: "₮",
              exp: 2,
              flag: "mn",
            },
            {
              code: "MOP",
              name: "Macau Pataca",
              symbol: "MOP$",
              exp: 2,
              flag: "mo",
            },
            {
              code: "MRO",
              name: "Mauritanian Ouguiya",
              symbol: "UM",
              exp: 2,
              flag: "mr",
            },
            {
              code: "MUR",
              name: "Mauritian rupee",
              symbol: "Rs",
              exp: 2,
              flag: "mu",
            },
            {
              code: "MVR",
              name: "Maldivian Rufiyaa",
              symbol: "rf",
              exp: 2,
              flag: "mv",
            },
            {
              code: "MWK",
              name: "Malawian Kwacha",
              symbol: "MK",
              exp: 2,
              flag: "mw",
            },
            {
              code: "MXN",
              name: "Mexico Peso",
              symbol: "$",
              exp: 2,
              flag: "mx",
            },
            {
              code: "MYR",
              name: "Malaysian Ringgit",
              symbol: "RM",
              exp: 2,
              flag: "my",
            },
            {
              code: "MZN",
              name: "Mozambican Metical",
              symbol: "MT",
              exp: 2,
              flag: "mz",
            },
            {
              code: "NAD",
              name: "Namibian Dollar",
              symbol: "$",
              exp: 2,
              flag: "na",
            },
            {
              code: "NGN",
              name: "Nigerian Naira",
              symbol: "₦",
              exp: 2,
              flag: "ng",
            },
            {
              code: "NIO",
              name: "Nicaraguan córdoba",
              symbol: "C$",
              exp: 2,
              flag: "ni",
            },
            {
              code: "NOK",
              name: "Norwegian krone",
              symbol: "kr",
              exp: 2,
              flag: "no",
            },
            {
              code: "NPR",
              name: "Nepalese Rupee",
              symbol: "Rs",
              exp: 2,
              flag: "np",
            },
            {
              code: "NZD",
              name: "New Zealand Dollar",
              symbol: "$",
              exp: 2,
              flag: "nz",
            },
            {
              code: "OMR",
              name: "Omani Rial",
              symbol: "ع.ر.",
              exp: 3,
              flag: "om",
            },
            {
              code: "PAB",
              name: "Balboa panamérn",
              symbol: "B/",
              exp: 2,
              flag: "pa",
            },
            {
              code: "PEN",
              name: "Peruvian nuevo sol",
              symbol: "S/",
              exp: 2,
              flag: "pe",
            },
            {
              code: "PGK",
              name: "Papua New Guinean Kina",
              symbol: "K",
              exp: 2,
              flag: "pg",
            },
            {
              code: "PHP",
              name: "Philippine Peso",
              symbol: "₱",
              exp: 2,
              flag: "ph",
            },
            {
              code: "PKR",
              name: "Pakistani Rupee",
              symbol: "Rs",
              exp: 2,
              flag: "pk",
            },
            {
              code: "PLN",
              name: "Polish złoty",
              symbol: "zł",
              exp: 2,
              flag: "pl",
            },
            {
              code: "PYG",
              name: "Paraguayan guarani",
              symbol: "₲",
              exp: 0,
              flag: "py",
            },
            {
              code: "QAR",
              name: "Qatari Riyal",
              symbol: "ق.ر ",
              exp: 2,
              flag: "qa",
            },
            {
              code: "RON",
              name: "Romanian leu",
              symbol: "lei",
              exp: 2,
              flag: "ro",
            },
            {
              code: "RSD",
              name: "Serbian Dinar",
              symbol: "РСД",
              exp: 2,
              flag: "rs",
            },
            {
              code: "RUB",
              name: "Russian Rouble",
              symbol: "₽",
              exp: 2,
              flag: "ru",
            },
            {
              code: "RWF",
              name: "Rwandan franc",
              symbol: "FRw, RF, R₣",
              exp: 0,
              flag: "rw",
            },
            {
              code: "SAR",
              name: "Saudi Arabian Riyal",
              symbol: "ر.س",
              exp: 2,
              flag: "sa",
            },
            {
              code: "SBD",
              name: "Solomon Islander Dollar",
              symbol: "SI$",
              exp: 2,
              flag: "sb",
            },
            {
              code: "SCR",
              name: "Seychellois Rupee",
              symbol: "Rs",
              exp: 2,
              flag: "sc",
            },
            {
              code: "SDG",
              name: "Sudanese Pound",
              symbol: "SDG",
              exp: 2,
              flag: "sd",
            },
            {
              code: "SEK",
              name: "Swedish krona",
              symbol: "kr",
              exp: 2,
              flag: "se",
            },
            {
              code: "SGD",
              name: "Singapore Dollar",
              symbol: "$",
              exp: 2,
              flag: "sg",
            },
            {
              code: "SLL",
              name: "Sierra Leonean Leone",
              symbol: "Le",
              exp: 2,
              flag: "sl",
            },
            {
              code: "SOS",
              name: "Somali Shilling",
              symbol: "S",
              exp: 2,
              flag: "so",
            },
            {
              code: "SRD",
              name: "Surinamese dollar",
              symbol: "$",
              exp: 2,
              flag: "sr",
            },
            {
              code: "SYP",
              name: "Syrian Pound",
              symbol: "£",
              exp: 2,
              flag: "sy",
            },
            {
              code: "SZL",
              name: "Swazi Lilangeni",
              symbol: "L or E",
              exp: 2,
              flag: "sz",
            },
            { code: "THB", name: "Thai Baht", symbol: "฿", exp: 2, flag: "th" },
            {
              code: "TJS",
              name: "Tajikistani somoni",
              symbol: "TJS",
              exp: 2,
              flag: "tj",
            },
            {
              code: "TMT",
              name: "Turkmenistan manat",
              symbol: "T",
              exp: 2,
              flag: "tm",
            },
            {
              code: "TND",
              name: "Tunisian Dinar",
              symbol: "TND",
              exp: 3,
              flag: "tn",
            },
            {
              code: "TOP",
              name: "Tongan Pa'anga",
              symbol: "T$",
              exp: 2,
              flag: "to",
            },
            {
              code: "TRY",
              name: "Turkish Lira",
              symbol: "₺",
              exp: 2,
              flag: "tr",
            },
            {
              code: "TTD",
              name: "Trinidadian dollar",
              symbol: "TT$",
              exp: 2,
              flag: "tt",
            },
            {
              code: "TWD",
              name: "Taiwan New Dollar",
              symbol: "NT$",
              exp: 2,
              flag: "tw",
            },
            {
              code: "TZS",
              name: "Tanzanian Shilling",
              symbol: "Sh",
              exp: 2,
              flag: "tz",
            },
            {
              code: "UAH",
              name: "Ukrainian Hryvnia",
              symbol: "₴",
              exp: 2,
              flag: "ua",
            },
            {
              code: "UGX",
              name: "Ugandan Shilling",
              symbol: "USh",
              exp: 0,
              flag: "ug",
            },
            { code: "USD", name: "US Dollar", symbol: "$", exp: 2, flag: "us" },
            {
              code: "UYU",
              name: "Uruguayan peso",
              symbol: "$U",
              exp: 2,
              flag: "uy",
            },
            {
              code: "UZS",
              name: "Uzbekistani som",
              symbol: "лв",
              exp: 2,
              flag: "uz",
            },
            {
              code: "VEF",
              name: "Venezuelan bolivar",
              symbol: "Bs",
              exp: 2,
              flag: "ve",
            },
            {
              code: "VND",
              name: "Vietnamese Dong",
              symbol: "₫",
              exp: 0,
              flag: "vn",
            },
            {
              code: "VUV",
              name: "Vanuatu Vatu",
              symbol: "VT",
              exp: 0,
              flag: "vu",
            },
            {
              code: "WST",
              name: "Samoan Tālā",
              symbol: "$",
              exp: 2,
              flag: "ws",
            },
            {
              code: "YER",
              name: "Yemeni Rial",
              symbol: "YER",
              exp: 2,
              flag: "ye",
            },
            {
              code: "ZAR",
              name: "South African Rand",
              symbol: "R",
              exp: 2,
              flag: "za",
            },
            {
              code: "ZMW",
              name: "Zambian Kwacha",
              symbol: "ZMK",
              exp: 2,
              flag: "zm",
            },
            {
              code: "ZWD",
              name: "Zimbabwean Dollar",
              symbol: "Z$",
              exp: 2,
              flag: "zw",
            },
            { code: "XAU", name: "Gold, troy ounce", symbol: "XAU", exp: 2 },
          ],
          skipDuplicates: true,
        })
        .catch((err) => {
          console.log(err);
        });
    }

    let activeCurrency = await prisma.activeCurrency.findMany();
    if (!activeCurrency.length) {
      
      console.log("CREATING ACTIVE CURRENCIES");
      await prisma.activeCurrency
        .createMany({
          data: [{ code: "USD", rate: 1 }],
          skipDuplicates: true,
        })
        .catch((err) => {
          console.log(err);
        });
    }

    let tranTypes = await prisma.transactionType.findMany();
    if (!tranTypes.length) {
      
      console.log("CREATING TRANSACTION TYPES");
      await prisma.transactionType
        .createMany({
          data: [{ name: "Expense" }, { name: "Income" }, { name: "Transfer" }],
          skipDuplicates: true,
        })
        .catch((err) => {
          console.log(err);
        });
    }

    let ctgs = await prisma.transactionCategory.findMany();
    if (!ctgs.length) {
      
      console.log("CREATING TRANSACTION CATEGORIES");
      await prisma.transactionCategory
        .createMany({
          data: [
            { transactionTypeId:1, name: "Rent" },
            { transactionTypeId:1, name: "Utilities" },
            { transactionTypeId:1, name: "Food" },
            { transactionTypeId:1, name: "Taxes" },
            { transactionTypeId:1, name: "Shopping" },
            { transactionTypeId:1, name: "Clothes" },
            { transactionTypeId:1, name: "Travel" },
            { transactionTypeId:1, name: "Misc" },
            { transactionTypeId:2, name: "Salary" },
            { transactionTypeId:2, name: "Bonus" },
            { transactionTypeId:2, name: "Savings Interest" },
            { transactionTypeId:2, name: "Misc" },

          ],
          skipDuplicates: true,
        })
        .catch((err) => {
          console.log(err);
        });
    }

    let accTypes = await prisma.accountType.findMany();
    if (!accTypes.length) {
      
      console.log("CREATING ACCOUNT TYPES");
      await prisma.accountType
        .createMany({
          data: [{ name: "Cash" }, { name: "Savings" }, { name: "Check" }, { name: "Credit" }],
          skipDuplicates: true,
        })
        .catch((err) => {
          console.log(err);
        });
    }    
  } catch {
    console.log("error seeding");
  }
};

seed();
